//! Nix text: a small JSON→Nix renderer and the four generated .nix files.

use std::collections::BTreeMap;

use crate::plan::Plan;
use crate::schema::Source;

/// Render a JSON value as a Nix expression, indented for nesting.
pub fn render(v: &serde_json::Value, indent: usize) -> String {
    use serde_json::Value as J;
    let pad = "  ".repeat(indent);
    match v {
        J::Null => "null".into(),
        J::Bool(b) => b.to_string(),
        J::Number(n) => n.to_string(),
        J::String(s) => quote(s),
        J::Array(items) => {
            if items.is_empty() {
                return "[ ]".into();
            }
            let inner: Vec<String> = items
                .iter()
                .map(|i| format!("{pad}  {}", render(i, indent + 1)))
                .collect();
            format!("[\n{}\n{pad}]", inner.join("\n"))
        }
        J::Object(map) => {
            if map.is_empty() {
                return "{ }".into();
            }
            let inner: Vec<String> = map
                .iter()
                .map(|(k, v)| format!("{pad}  {} = {};", attr(k), render(v, indent + 1)))
                .collect();
            format!("{{\n{}\n{pad}}}", inner.join("\n"))
        }
    }
}

pub fn quote(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    let mut chars = s.chars().peekable();
    while let Some(c) = chars.next() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\t' => out.push_str("\\t"),
            '$' if chars.peek() == Some(&'{') => out.push_str("\\$"),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

/// An attribute name, quoted unless it is a plain identifier.
pub fn attr(name: &str) -> String {
    let ident = !name.is_empty()
        && !name.chars().next().unwrap().is_ascii_digit()
        && name
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '-' || c == '\'');
    if ident && name != "in" && name != "let" && name != "with" && name != "rec" && name != "inherit" {
        name.to_string()
    } else {
        quote(name)
    }
}

/// A dotted option path as a Nix attribute path.
pub fn attr_path(path: &str) -> String {
    path.split('.').map(attr).collect::<Vec<_>>().join(".")
}

pub fn flake_nix(plan: &Plan) -> String {
    let host = &plan.host.name;
    let mut imports = String::new();
    for m in &plan.modules {
        imports.push_str(&format!("        homelab-modules.nixosModules.{}\n", attr(m)));
    }
    format!(
        "{{\n  \
           description = \"{host} — homelab built from homelab-modules\";\n\n  \
           inputs = {{\n    \
             nixpkgs.url = \"github:nixos/nixpkgs/nixos-26.05\";\n    \
             homelab-modules.url = {lib};\n    \
             sops-nix = {{\n      \
               url = \"github:Mic92/sops-nix\";\n      \
               inputs.nixpkgs.follows = \"nixpkgs\";\n    \
             }};\n    \
             disko = {{\n      \
               url = \"github:nix-community/disko\";\n      \
               inputs.nixpkgs.follows = \"nixpkgs\";\n    \
             }};\n  \
           }};\n\n  \
           outputs = {{ nixpkgs, homelab-modules, sops-nix, disko, ... }}: {{\n    \
             nixosConfigurations.{host} = nixpkgs.lib.nixosSystem {{\n      \
               system = \"{system}\";\n      \
               modules = [\n        \
                 disko.nixosModules.disko\n        \
                 sops-nix.nixosModules.sops\n        \
                 ./hosts/{host}\n        \
                 ./homelab-values.nix\n\n        \
                 # From the library — one line per concern. Add or remove here.\n\
                 {imports}      \
               ];\n    \
             }};\n  \
           }};\n\
         }}\n",
        host = attr(host),
        system = plan.host.system,
        lib = quote(&plan.library_url),
        imports = imports,
    )
}

pub fn values_nix(plan: &Plan) -> String {
    let mut s = String::from(
        "# Your values for the homelab-modules library, plus the sops declarations its\n\
         # modules read through the homelab.*File options. Generated by\n\
         # homelab-configure; edit freely — it is plain NixOS configuration.\n\
         { config, ... }:\n\n{\n",
    );
    // Values grouped for readability: top-level leaves (domain, adminUser)
    // under "site", the rest by their second path segment.
    let mut groups: BTreeMap<String, Vec<(&String, &serde_json::Value)>> = BTreeMap::new();
    for (k, v) in &plan.values {
        let group = if k.matches('.').count() == 1 {
            "site".to_string()
        } else {
            k.split('.').nth(1).unwrap_or("").to_string()
        };
        groups.entry(group).or_default().push((k, v));
    }
    for (group, entries) in groups {
        s.push_str(&format!("  # ── {group} ──\n"));
        for (k, v) in entries {
            s.push_str(&format!("  {} = {};\n", attr_path(k), render(v, 1)));
        }
        s.push('\n');
    }
    if !plan.secrets.is_empty() {
        s.push_str("  # ── secrets: option → path, and the sops declaration behind each ──\n");
        for sp in &plan.secrets {
            s.push_str(&format!(
                "  {} = config.sops.secrets.{}.path;\n",
                attr_path(&sp.option),
                quote(&sp.name)
            ));
        }
        s.push('\n');
        for sp in &plan.secrets {
            s.push_str(&format!(
                "  sops.secrets.{} = {{\n    sopsFile = ./secrets/{}.yaml;\n    key = {};\n",
                quote(&sp.name),
                sp.name,
                quote(&sp.name)
            ));
            if sp.owner != "root" {
                s.push_str(&format!("    owner = {};\n", quote(&sp.owner)));
            }
            if sp.source == Source::FirstBoot {
                s.push_str("    # CHANGEME placeholder until PHASE-2.md is done.\n");
            }
            s.push_str("  };\n");
        }
    }
    s.push_str("}\n");
    s
}

pub fn host_nix(plan: &Plan, admin_user: &str, admin_hash: &str) -> String {
    let h = plan.host;
    let keys: Vec<String> = h.ssh_authorized_keys.iter().map(|k| format!("      {}", quote(k))).collect();
    format!(
        "# {name} — the host itself: identity, the admin login, ssh, sops. Values the\n\
         # library reads are in ../../homelab-values.nix; disk layout in ./disko.nix.\n\
         {{ ... }}:\n\n\
         {{\n  \
           imports = [ ./disko.nix ./hardware.nix ];\n\n  \
           networking.hostName = {name_q};\n  \
           time.timeZone = {tz};\n  \
           nixpkgs.hostPlatform = {system};\n  \
           system.stateVersion = {sv};\n\n  \
           # The admin. SSH keys are the intended way in; the console password is in\n  \
           # FIRST-LOGIN.md (yescrypt hash here, so it is safe to commit).\n  \
           users.users.{user} = {{\n    \
             isNormalUser = true;\n    \
             extraGroups = [ \"wheel\" ];\n    \
             hashedPassword = {hash};\n    \
             openssh.authorizedKeys.keys = [\n{keys}\n    ];\n  \
           }};\n  \
           services.openssh = {{\n    \
             enable = true;\n    \
             settings.PasswordAuthentication = false;\n    \
             settings.PermitRootLogin = \"no\";\n  \
           }};\n\n  \
           # sops-nix decrypts with the host's SSH key — the one nixos-anywhere\n  \
           # installed from extra-files/, whose age recipient is in ../../.sops.yaml.\n  \
           sops.age.sshKeyPaths = [ \"/etc/ssh/ssh_host_ed25519_key\" ];\n\
         }}\n",
        name = h.name,
        name_q = quote(&h.name),
        tz = quote(&h.time_zone),
        system = quote(&h.system),
        sv = quote(&h.state_version),
        user = attr(admin_user),
        hash = quote(admin_hash),
        keys = keys.join("\n"),
    )
}

pub fn disko_nix(plan: &Plan) -> String {
    let h = plan.host;
    let mut s = format!(
        "# Disk layout for disko — applied by nixos-anywhere at install. EVERYTHING on\n\
         # these devices is erased. GPT, a 512M ESP, ext4 root; each data disk is one\n\
         # ext4 filesystem at /mnt/disks/<name> (pool them with mergerfs-pools if you\n\
         # imported it: homelab.pools.<pool>.branches = \"/mnt/disks/*\").\n\
         {{ ... }}:\n\n\
         {{\n  \
           disko.devices.disk = {{\n    \
             main = {{\n      \
               type = \"disk\";\n      \
               device = {disk};\n      \
               content = {{\n        \
                 type = \"gpt\";\n        \
                 partitions = {{\n          \
                   ESP = {{\n            \
                     size = \"512M\";\n            \
                     type = \"EF00\";\n            \
                     content = {{\n              \
                       type = \"filesystem\";\n              \
                       format = \"vfat\";\n              \
                       mountpoint = \"/boot\";\n              \
                       mountOptions = [ \"umask=0077\" ];\n            \
                     }};\n          \
                   }};\n          \
                   root = {{\n            \
                     size = \"100%\";\n            \
                     content = {{\n              \
                       type = \"filesystem\";\n              \
                       format = \"ext4\";\n              \
                       mountpoint = \"/\";\n            \
                     }};\n          \
                   }};\n        \
                 }};\n      \
               }};\n    \
             }};\n",
        disk = quote(&h.disk)
    );
    for d in &h.data_disks {
        s.push_str(&format!(
            "    {name} = {{\n      \
               type = \"disk\";\n      \
               device = {dev};\n      \
               content = {{\n        \
                 type = \"gpt\";\n        \
                 partitions.data = {{\n          \
                   size = \"100%\";\n          \
                   content = {{\n            \
                     type = \"filesystem\";\n            \
                     format = \"ext4\";\n            \
                     mountpoint = \"/mnt/disks/{mnt}\";\n          \
                   }};\n        \
                 }};\n      \
               }};\n    \
             }};\n",
            name = attr(&d.name),
            dev = quote(&d.device),
            mnt = d.name
        ));
    }
    s.push_str("  };\n}\n");
    s
}

pub fn hardware_placeholder() -> String {
    "# Replaced by nixos-anywhere --generate-hardware-config at install (kernel\n\
     # modules, CPU microcode, …). Until then the system still evaluates: disko\n\
     # declares the filesystems, and the defaults boot most x86 machines.\n\
     { ... }:\n\n{\n  boot.loader.systemd-boot.enable = true;\n  boot.loader.efi.canTouchEfiVariables = true;\n}\n"
        .into()
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn scalars_and_strings() {
        assert_eq!(render(&json!("a"), 0), "\"a\"");
        assert_eq!(render(&json!(true), 0), "true");
        assert_eq!(render(&json!(7), 0), "7");
        assert_eq!(render(&json!(null), 0), "null");
        assert_eq!(quote("say \"hi\" ${x} \\"), "\"say \\\"hi\\\" \\${x} \\\\\"");
        assert_eq!(quote("$5"), "\"$5\"");
    }

    #[test]
    fn nested_structures() {
        let v = json!({"media": {"mountpoint": "/mnt/media", "members": ["D1", "D2"]}, "x.y": 1});
        let out = render(&v, 0);
        assert_eq!(
            out,
            "{\n  media = {\n    members = [\n      \"D1\"\n      \"D2\"\n    ];\n    mountpoint = \"/mnt/media\";\n  };\n  \"x.y\" = 1;\n}"
        );
        assert_eq!(render(&json!([]), 0), "[ ]");
        assert_eq!(render(&json!({}), 0), "{ }");
    }

    #[test]
    fn attribute_names() {
        assert_eq!(attr("domain"), "domain");
        assert_eq!(attr("arr-net"), "arr-net");
        assert_eq!(attr("with"), "\"with\"");
        assert_eq!(attr("1st"), "\"1st\"");
        assert_eq!(attr("a.b"), "\"a.b\"");
        assert_eq!(attr_path("homelab.arrStack.root"), "homelab.arrStack.root");
    }
}
